services:
  postgres:
    image: postgres:15-alpine
    container_name: backlogus-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: backlogus_db
      POSTGRES_USER: backlogus_user
      POSTGRES_PASSWORD: backlogus_password
    ports:
      - "5432:5432"
    volumes:
      - backlogus-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backlogus_user -d backlogus_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backlogus-db:
