version: '3.8'
services:
  app:
    image: ghcr.io/nelsonportela/backlogus:${TAG:-latest}
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/backlogus_db
      - JWT_SECRET=your-super-secret-jwt-key
      - IGDB_CLIENT_ID=your-igdb-client-id
      - IGDB_ACCESS_TOKEN=your-igdb-access-token
      - TMDB_API_KEY=your-tmdb-api-key
    ports:
      - "3001:3001"
    depends_on:
      - db
    # Uncomment if you want to persist image cache
    # volumes:
    #   - ./backend/cache/images:/app/backend/cache/images

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=backlogus_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - backlogus-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  backlogus-db-data:
